import json
from pathlib import Path
from typing import Dict
from core.auditor import AuditSummary


class AuditReporter:
    """
    Formats and exports security audit findings into Terminal, Markdown, and JSON.
    """

    def __init__(self, summary: AuditSummary):
        self.summary = summary

    def generate_terminal_summary(self) -> str:
        lines = []
        lines.append("=" * 70)
        lines.append("              AUTHSCOPE: API ACCESS CONTROL AUDIT REPORT")
        lines.append("=" * 70)
        lines.append(f"  Total Endpoints Scanned : {self.summary.total_endpoints_scanned}")
        lines.append(f"  Total Test Cases Ran    : {self.summary.total_tests_executed}")
        lines.append("-" * 70)
        lines.append("  FINDINGS BREAKDOWN:")
        for sev, count in self.summary.findings_count.items():
            lines.append(f"    - {sev:<9}: {count}")
        lines.append("=" * 70)

        if not self.summary.findings:
            lines.append("\n  [+] No authorization flaws identified. All endpoints enforced controls.")
        else:
            lines.append("\n  IDENTIFIED ACCESS CONTROL VULNERABILITIES:")
            for idx, f in enumerate(self.summary.findings, 1):
                lines.append(f"\n  [{idx}] [{f.severity}] {f.title}")
                lines.append(f"      Endpoint : {f.method} {f.endpoint}")
                lines.append(f"      Standard : {f.owasp_id}")
                lines.append(f"      Details  : {f.details}")
                lines.append(f"      Reproduce: {f.reproduction_curl}")

        lines.append("\n" + "=" * 70)
        return "\n".join(lines)

    def export_json(self, output_path: str):
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.summary.model_dump_json(indent=2), encoding="utf-8")

    def export_markdown(self, output_path: str):
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        md = []
        md.append("# API Authorization & Access Control Audit Report\n")
        md.append("> **Generated by AuthScope Engine** | Target Standard: OWASP API Security Top 10 (2023)\n")
        md.append("## 1. Executive Summary\n")
        md.append(f"- **Total Endpoints Assessed:** `{self.summary.total_endpoints_scanned}`")
        md.append(f"- **Total Test Variations Executed:** `{self.summary.total_tests_executed}`")
        md.append(f"- **Critical Vulnerabilities:** `{self.summary.findings_count.get('CRITICAL', 0)}`")
        md.append(f"- **High Vulnerabilities:** `{self.summary.findings_count.get('HIGH', 0)}`")
        md.append(f"- **Medium Vulnerabilities:** `{self.summary.findings_count.get('MEDIUM', 0)}`\n")

        md.append("### Severity Distribution\n")
        md.append("| Severity | Count | Primary Impact |")
        md.append("| :--- | :--- | :--- |")
        md.append(f"| **CRITICAL** | {self.summary.findings_count.get('CRITICAL', 0)} | Unauthorized tenant data access (BOLA) / Admin takeover |")
        md.append(f"| **HIGH** | {self.summary.findings_count.get('HIGH', 0)} | Function-level privilege escalation (BFLA) |")
        md.append(f"| **MEDIUM** | {self.summary.findings_count.get('MEDIUM', 0)} | Missing authentication on sensitive endpoints |")
        md.append("\n---\n")

        md.append("## 2. Vulnerability Findings & Reproduction\n")
        if not self.summary.findings:
            md.append("No access control vulnerabilities discovered.\n")
        else:
            for idx, finding in enumerate(self.summary.findings, 1):
                md.append(f"### {idx}. [{finding.severity}] {finding.title}\n")
                md.append(f"- **Endpoint:** `{finding.method} {finding.endpoint}`")
                md.append(f"- **Standard:** `{finding.owasp_id}`")
                md.append(f"- **Vulnerability Class:** `{finding.vulnerability_type}`\n")
                md.append(f"**Description:**  \n{finding.details}\n")
                
                md.append("**Reproduction (cURL):**")
                md.append(f"```bash\n{finding.reproduction_curl}\n```\n")
                
                md.append("**Remediation Guidance:**  \n")
                md.append(f"{finding.remediation}\n")
                md.append("---\n")

        path.write_text("\n".join(md), encoding="utf-8")
